[package]
name = "seresa"
version = "0.1.0"
edition = "2018"

[dependencies]
freechains = "0.3.1"
clap = "2.33.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.13.0"
